version: '2'

volumes:
  nextcloud:
  apps:
  config:
  data:
  db:

services:
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    build: .
    ports:
      - 8081:80
    links:
      - nextcloud-db
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/nextcloud/custom_apps     
      - config:/var/www/nextcloud/config     
      - data:/var/www/nextcloud/data
    restart: always
